# Generated by Django 4.1.13 on 2024-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
