# Generated by Django 4.1.13 on 2024-05-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0003_remove_customer_category_alter_customer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='titles',
        ),
    ]
