# Generated by Django 4.1.13 on 2024-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0004_rename_title_product_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titles',
            new_name='title',
        ),
    ]
