# Generated by Django 4.1.13 on 2024-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0005_rename_titles_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='no-profile.png', upload_to='profile_images/'),
        ),
    ]
