# Generated by Django 4.1.13 on 2024-05-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0010_rename_condition_product_p_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_condition',
            new_name='condition',
        ),
    ]
