# Generated by Django 5.0.6 on 2024-05-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0011_rename_p_condition_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_member1', to='newlevelsapi.customer')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_member2', to='newlevelsapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newlevelsapi.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='newlevelsapi.customer')),
            ],
        ),
    ]
