# Generated by Django 4.2 on 2024-05-17 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0012_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(default='da7f872c-25e0-450e-8b59-20b217d65adf', on_delete=django.db.models.deletion.CASCADE, to='newlevelsapi.product'),
        ),
    ]
