# Generated by Django 4.2 on 2024-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlevelsapi', '0013_chatroom_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='/v1/no-profile.png', upload_to='profile_images/'),
        ),
    ]
